type: web_service
name: ecommerce-return-api
env: docker
dockerfile_path: deployment/Dockerfile
build_command: pip install -r requirements.txt
start_command: uvicorn app:app --host 0.0.0.0 --port 10000
plan: free
region: oregon
